### ISSUE TITLE
App run on Android 4.4.4 Tiantian Simulator had crash.

### ISSUE THREAD

**Issue by beforenight** [AllenCoder/AppManager#3]
`05-17 11:53:10.381 24458-24458/com.allen.appmanager E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.allen.appmanager, PID: 24458
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.allen.appmanager/com.allen.appmanager.MainActivity}: android.view.InflateException: Binary XML file line #32: Error inflating class Toolbar
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2190)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2335)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:141)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: android.view.InflateException: Binary XML file line #32: Error inflating class Toolbar
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                          at com.allen.appmanager.MainActivity.onCreate(MainActivity.java:85)
                                                                          at android.app.Activity.performCreate(Activity.java:5247)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2335) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.Toolbar" on path: DexPathList[[zip file "/data/app/com.allen.appmanager-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.allen.appmanager-1, /system/lib, /system/lib/arm]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:559)
                                                                          at android.view.LayoutInflater.onCreateView(LayoutInflater.java:652)
                                                                          at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:66)
                                                                          at android.view.LayoutInflater.onCreateView(LayoutInflater.java:669)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:694)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                          at com.allen.appmanager.MainActivity.onCreate(MainActivity.java:85) 
                                                                          at android.app.Activity.performCreate(Activity.java:5247) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2154) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2335) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:141) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5103) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                                                                          at dalvik.system.NativeStart.main(Native Method) `

Device info :
![image](https://cloud.githubusercontent.com/assets/24861685/26137966/64bbe614-3af8-11e7-8fda-96fdff31b0d4.png)

**Comment by AllenCoder** [comment]
应该是模拟器 的原因，不兼容AppcompatActviity
